// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    public interface ITesteDB : System.IDisposable
    {
        System.Data.Entity.DbSet<Table1> Table1 { get; set; } // Table1
        System.Data.Entity.DbSet<Table1To6> Table1To6 { get; set; } // Table1To6
        System.Data.Entity.DbSet<Table2> Table2 { get; set; } // Table2
        System.Data.Entity.DbSet<Table3> Table3 { get; set; } // Table3
        System.Data.Entity.DbSet<Table4> Table4 { get; set; } // Table4
        System.Data.Entity.DbSet<Table5> Table5 { get; set; } // Table5
        System.Data.Entity.DbSet<Table6> Table6 { get; set; } // Table6
        System.Data.Entity.DbSet<Table7> Table7 { get; set; } // Table7
        System.Data.Entity.DbSet<Table8> Table8 { get; set; } // Table8
        System.Data.Entity.DbSet<Table9> Table9 { get; set; } // Table9

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
