// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table2
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table2
    {
        public int Table2ID { get; set; } // Table2ID (Primary key)
        public int? Table1ID { get; set; } // Table1ID

        // Foreign keys

        /// <summary>
		/// Parent Table1 pointed by [Table2].([Table1ID]) (FK_Table2_Table1ID)
		/// </summary>
        public virtual Table1 Table1 { get; set; } // FK_Table2_Table1ID
    }

}
// </auto-generated>
