// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table7
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table7Configuration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Table7>
    {
        public Table7Configuration()
            : this("dbo")
        {
        }

        public Table7Configuration(string schema)
        {
            ToTable("Table7", schema);
            HasKey(x => new { x.Table7AID, x.Table7BID });

            Property(x => x.Table7AID).HasColumnName(@"Table7AID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Table7BID).HasColumnName(@"Table7BID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Info).HasColumnName(@"Info").HasColumnType("int").IsOptional();
            HasOptional(x => x.Table8).WithRequired().Map(m => m.MapKey("Table7AID", "Table7BID"));
            HasOptional(x => x.Table9).WithRequired().Map(m => m.MapKey("Table7AID", "Table7BID"));
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
