// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table9
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table9
    {
        public int Table7BID { get; set; } // Table7BID (Primary key)
        public int Table7AID { get; set; } // Table7AID (Primary key)
        public int? Info { get; set; } // Info

        // Foreign keys

        /// <summary>
		/// Parent Table7 pointed by [Table9].([Table7BID], [Table7AID]) (FK_Table9_Table7)
		/// </summary>
        public virtual Table7 Table7 { get; set; } // FK_Table9_Table7
    }

}
// </auto-generated>
