// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table5
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table5Configuration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Table5>
    {
        public Table5Configuration()
            : this("dbo")
        {
        }

        public Table5Configuration(string schema)
        {
            ToTable("Table5", schema);
            HasKey(x => x.Table5ID);

            Property(x => x.Table5ID).HasColumnName(@"Table5ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Info).HasColumnName(@"Info").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.Table1).WithOptional(b => b.Table5).WillCascadeOnDelete(false); // FK_Table5_Table1ID
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
