// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table4
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table4
    {
        public int Table4ID { get; set; } // Table4ID (Primary key)
        public int? Info { get; set; } // Info

        // Foreign keys

        /// <summary>
		/// Parent Table1 pointed by [Table4].([Info]) (FK_Table4_Table1Info)
		/// </summary>
        public virtual Table1 Table1 { get; set; } // FK_Table4_Table1Info
    }

}
// </auto-generated>
