// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table1To6
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table1To6
    {
        public int Table1ID { get; set; } // Table1ID (Primary key)
        public int Table6ID { get; set; } // Table6ID (Primary key)
        public int? Info { get; set; } // Info

        // Foreign keys

        /// <summary>
		/// Parent Table1 pointed by [Table1To6].([Table1ID]) (FK_Table1To6_Table1ID)
		/// </summary>
        public virtual Table1 Table1 { get; set; } // FK_Table1To6_Table1ID
        /// <summary>
		/// Parent Table6 pointed by [Table1To6].([Table6ID]) (FK_Table1To6_Table6ID)
		/// </summary>
        public virtual Table6 Table6 { get; set; } // FK_Table1To6_Table6ID
    }

}
// </auto-generated>
