// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table1To6
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table1To6Configuration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Table1To6>
    {
        public Table1To6Configuration()
            : this("dbo")
        {
        }

        public Table1To6Configuration(string schema)
        {
            ToTable("Table1To6", schema);
            HasKey(x => new { x.Table1ID, x.Table6ID });

            Property(x => x.Table1ID).HasColumnName(@"Table1ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Table6ID).HasColumnName(@"Table6ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Info).HasColumnName(@"Info").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.Table1).WithMany(b => b.Table1To6).HasForeignKey(c => c.Table1ID).WillCascadeOnDelete(false); // FK_Table1To6_Table1ID
            HasRequired(a => a.Table6).WithMany(b => b.Table1To6).HasForeignKey(c => c.Table6ID).WillCascadeOnDelete(false); // FK_Table1To6_Table6ID
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
