// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table7
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table7
    {
        public int Table7AID { get; set; } // Table7AID (Primary key)
        public int Table7BID { get; set; } // Table7BID (Primary key)
        public int? Info { get; set; } // Info

        // Reverse navigation

        /// <summary>
		/// Parent (One-to-One) Table7 pointed by [Table8].("[Table7AID], [Table7BID]") (FK_Table8_Table7)
		/// </summary>
        public virtual Table8 Table8 { get; set; } // Table8.FK_Table8_Table7
        /// <summary>
		/// Parent (One-to-One) Table7 pointed by [Table9].("[Table7AID], [Table7BID]") (FK_Table9_Table7)
		/// </summary>
        public virtual Table9 Table9 { get; set; } // Table9.FK_Table9_Table7
    }

}
// </auto-generated>
