// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table9
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table9Configuration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Table9>
    {
        public Table9Configuration()
            : this("dbo")
        {
        }

        public Table9Configuration(string schema)
        {
            ToTable("Table9", schema);
            HasKey(x => new { x.Table7BID, x.Table7AID });

            //Property(x => x.Table7BID).HasColumnName(@"Table7BID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            //Property(x => x.Table7AID).HasColumnName(@"Table7AID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Info).HasColumnName(@"Info").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.Table7).WithOptional(b => b.Table9)
                //.Map(m => m.MapKey("Table7AID", "Table7BID"))
                .WillCascadeOnDelete(false); // FK_Table9_Table7
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
