// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table6
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table6
    {
        public int Table6ID { get; set; } // Table6ID (Primary key)
        public int? Info { get; set; } // Info

        // Reverse navigation

        /// <summary>
		/// Table1To6 childs where Table1To6.[Table6ID] point to this entity (FK_Table1To6_Table6ID)
		/// </summary>
        public virtual System.Collections.Generic.ICollection<Table1To6> Table1To6 { get; set; } = new System.Collections.Generic.List<Table1To6>(); // Table1To6.FK_Table1To6_Table6ID
    }

}
// </auto-generated>
