// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table1
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table1
    {
        public int Table1ID { get; set; } // Table1ID (Primary key)
        public int? Info { get; set; } // Info

        // Reverse navigation

        /// <summary>
		/// Table2 childs where Table2.[Table1ID] point to this entity (FK_Table2_Table1ID)
		/// </summary>
        public virtual System.Collections.Generic.ICollection<Table2> Table2 { get; set; } = new System.Collections.Generic.List<Table2>(); // Table2.FK_Table2_Table1ID
        /// <summary>
		/// Table3 childs (Many-to-Many) mapped by Table Table1To3
		/// </summary>
        public virtual System.Collections.Generic.ICollection<Table3> Table3 { get; set; } = new System.Collections.Generic.List<Table3>(); // Many to many mapping
        /// <summary>
		/// Parent (One-to-One) Table1 pointed by [Table5].([Table5ID]) (FK_Table5_Table1ID)
		/// </summary>
        public virtual Table5 Table5 { get; set; } // Table5.FK_Table5_Table1ID
    }

}
// </auto-generated>
