// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApplication1.Entities
{

    // Table3
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Table3
    {
        public int Table3ID { get; set; } // Table3ID (Primary key)
        public int? Info { get; set; } // Info

        // Reverse navigation

        /// <summary>
		/// Table1 childs (Many-to-Many) mapped by Table Table1To3
		/// </summary>
        public virtual System.Collections.Generic.ICollection<Table1> Table1 { get; set; } = new System.Collections.Generic.List<Table1>(); // Many to many mapping
    }

}
// </auto-generated>
